### ISSUE TITLE
Not syncing across Windows

### ISSUE THREAD

**Issue by NathanDalley** [nitrous-io/nitrogen-dist#10]
I've installed a fresh copy of Atom.io and Nitrogen 0.1.3 on 3 laptops running 64bit versions of Windows 7, Windows 8.1 and Windows 10, in each case I have the same experience when trying to sync.

On the client the folder 'project-name' is created with a .unison subfolder, then Nsync shows this following error and stops syncing.
Log:
[nsync event] {"name":"container.sync-enabled","data":{"slug":"project-name"}}
[nsync event] {"name":"container.sync-started","data":{"slug":"project-name"}}
[nsync error] sync: Unison command failed: exit status 2
[nsync event] {"name":"container.sync-finished","data":{"slug":"project-name"}}

Stopping and starting the sync results with the same messages and no errors in unison.log
No problems logging in, using the shell or port forwarding.

I'm going to have a look at possible problems with 32bit unison working on a 64-bit machine

**Comment by styner32** [comment]
Thank you for your detailed report.

Could you change environment variable `NSYNC_LOG_LEVEL` to `debug` and restart atom?
It will show more logs.

**Comment by NathanDalley** [comment]
Interesting: 
[nsync debug] UNISON 2.40.69 started propagating changes at 15:00:17.00 on 29 Jan 2016
[nsync debug] Fatal error: Error in getLogch:
/Users/sunjinlee/unison.log: No such file or directory
[nsync debug] Fatal error: exception Util.Fatal("Error in getLogch:
/Users/sunjinlee/unison.log: No such file or directory")
[nsync error] sync: Unison command failed: exit status 2
[nsync debug] Sync end!

**Comment by NathanDalley** [comment]
[nsync debug] C:\Users\ADMINI~1\ATOM~1\packages\nitrogen\nsync\win32\NITROU~1.EXE C:\Users\Administrator\Nitrous\xyz-123\projectname-123456 ssh://nitrous@xyz-123.nitrouspro.com:32777/code -auto=true -batch=true -dumbtty=true -confirmbigdel=false -confirmmerge=false -log=true **-logfile=/Users/sunjinlee/unison.log**  -perms=777 -prefer ssh://nitrous@xyz-123.nitrouspro.com:32777/code -rsrc=false -servercmd=/nitrous/nitrous-unison -sshargs -i C:\Users\Administrator\Nitrous\SSH\\\Keys\xyz\id_rsa -T -sshcmd C:\Users\ADMINI~1\ATOM~1\packages\nitrogen\nsync\win32\NSYNC-~1.EXE -times=true -ignore Name {.unison,.git,.svn,.hg,CVS,.DS_Store,.AppleDouble,.LSOverride,.Spotlight-V100,.Trashes,Thumbs.db,desktop.ini,_.lock,_.sock,_.pid,_.sw?,.unison_,.__,*~} -ignore Path {tmp\sessions,tmp\cache,tmp\pids,tmp\sockets} -ignorecase=true -ui=text -fastcheck=true

**Comment by styner32** [comment]
We just released v0.1.4 to fix the issue. Could you update and try it again?

**Comment by NathanDalley** [comment]
Thanks, I can confirm that the Syncing is now working on the Windows 10 machine; its not 100%, but that's a different issue.  I'll raise a new issue once I've investigated a bit more.
