### ISSUE TITLE
Nitrous Login question

### ISSUE THREAD

**Issue by jdevsd** [nitrous-io/nitrogen-dist#38]
I am running the latest Atom and Nitrogen packages and am unable to find a way to login to Nitrous.  I have used this package in the past but have since uninstalled and reinstalled it.  Any help is greatly appreciated. 

Thanks

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --

Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

## Links:

[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --

hi.

Sorry for the trouble.

Could you share any screenshots from your atom ?

If you can't see the login button, you can open developer tool (View

> Developer > Toggle Developer Tool) and run 
> 
> ## "localStorage.clear()" restart atom
> 
> Sunjin
> support@nitrous.io

How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]

## Links:

[1]
https://secure.helpscout.net/satisfaction/86419082/record/576888010/1/
[2]
https://secure.helpscout.net/satisfaction/86419082/record/576888010/2/
[3]
https://secure.helpscout.net/satisfaction/86419082/record/576888010/3/

**Comment by jdevsd** [comment]
Something worked!!  Thank you.

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --

Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

## Links:

[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq
