### ISSUE TITLE
Failed to get container info: container info not found

### ISSUE THREAD

**Issue by ryanjafari** [nitrous-io/nitrogen-dist#4]
Hi gang,

Been having trouble getting Nitrogen to load my containers at all (not able to see files or the shell).

When I try to enable "File Sync" I get this error in my Debug Window:

```
Running Nsync...
[nsync event] {"name":"pid","data":25733}
[nsync event] {"name":"listening","data":64876}
[nsync error] Failed to get container info: container info not found
[nsync error] Failed to start sync: container info not found
[nsync error] Failed to get container info: container info not found
[nsync error] Failed to start sync: container info not found
```

One thing I thought to check was ssh keys:

It seems the Nitrogen plugin is automatically creating and registering a public SSH key with Nitrous, because I see it showing up on the Nitrous SSH settings dashboard as: ryanjafari@Ryan-Jafaris-MacBook.local.desktop.nitrous.io.

I usually manage my SSH keys using an ~/.ssh/config file, so not sure if the problem has anything to do with that. Meaning, I usually specify the keys I want to use in there and their location for a specific host. I don’t think I’m using ssh-agent at all to manage keys.

I was looking for a location of where the Nitrogen plugin is storing this generated key set. Any ideas where it might be so I can try adding it to my ~/.ssh/config to see if that does anything?

Additional info (thought of it so threw it in here):
- I have disabled all "Community Packages" except for Nitrogen, and restarted. No "Development Packages," although I do have "Core Packages" enabled.
- My PATH is: `$PATH=/usr/local/opt/rbenv/shims:/usr/local/heroku/bin:/usr/local/bin:~/.bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin`
- Another thing to note is that my Atom installation is currently managed by Homebrew's cask plugin, and symlinked into `"/Applications"`
- I have the shell tools installed for Atom
- OS X El Capitan 10.11.2
- Atom 1.3.3

The availability of this plugin was such a nice surprise to me from AJ the other day, so thanks for working on this... makes coding w/ Nitrous open up to more possibilities :)

**Comment by styner32** [comment]
Hi @ryanjafari 

It shouldn't have ssh key issue with file sync if you have signed in correctly and we generate ssh key in `$HOME/Nitrous` folder and use is directly, so you don't have to do anything with `~/.ssh/config`.

To use shell, ssh port need to be open in your container. Could you add port 22 on https://www.nitrous.io/app/#/dashboard/workstations/ryanjafari-7164/projects/ruby-on-rails-145134/ports?

We will improve error message.

Thanks

**Comment by ryanjafari** [comment]
Ok, that did the trick! Yes, improving the error message will help.
